{
 "title": "POX_live",
 "tags": [ "POX" ],
 "time": { "from": "now/d-5h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "time_interval",
    "query": "1s,10s,30s,1m,10m,30m,1h,6h,12h,1d,15d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "BPM",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "BPM",
     "query": "SELECT mean(\"value\") FROM \"BPM\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SpO₂",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "SPO2",
     "query": "SELECT mean(\"value\") FROM \"BPM\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ø BPM",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "BPM",
     "query": "SELECT mean(\"value\") FROM \"BPM\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ø SpO₂",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "SPO2",
     "query": "SELECT mean(\"value\") FROM \"BPM\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 1, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BPM",
     "query": "SELECT max(\"value\") FROM \"BPM\" WHERE $timeFilter GROUP BY time($time_interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BPM",
     "query": "SELECT min(\"value\") FROM \"BPM\" WHERE $timeFilter GROUP BY time($time_interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BPM",
     "query": "SELECT mean(\"value\") FROM \"BPM\" WHERE $timeFilter GROUP BY time($time_interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SpO₂",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 1, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SPO2",
     "query": "SELECT max(\"value\") FROM \"SPO2\" WHERE $timeFilter GROUP BY time($time_interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SPO2",
     "query": "SELECT min(\"value\") FROM \"SPO2\" WHERE $timeFilter GROUP BY time($time_interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SPO2",
     "query": "SELECT mean(\"value\") FROM \"SPO2\" WHERE $timeFilter GROUP BY time($time_interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 21 },
   "targets": [
    {
     "alias": "high SPO2 - 001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND value::integer | 1 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "low SPO2 - 002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND  value::integer | 2 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "high BPM - 004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND  value::integer | 4 = value GROUP BY time($time_interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "low BPM - 008",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND  value::integer | 8 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Alarm raised - 010",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND  value::integer | 16 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Alarm muted - 020",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND  value::integer | 32 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "low Batt - 040",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND  value::integer | 64 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "unknown - 080",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT count(value) FROM ALARM WHERE $timeFilter AND  value::integer | 128 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exc",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "No Sensor - 001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 1 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Defective Sensor - 002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 2 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Low Perfusion - 004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 4 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Pulse Search - 008",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 8 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Interference - 010",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 16 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Sensor Off - 020 ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 32 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Ambient Light - 040",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 64 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Unrecognized Sensor - 080",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 128 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Low Signal IQ - 400",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ALARM",
     "query": "SELECT COUNT(value) FROM EXC WHERE  $timeFilter AND value::integer | 1024 = value GROUP BY time($time_interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}